deployment:
  tasks:
    - export DEPLOYPATH=/home/g1qpy8ym7ki5/repositories/TherapyWithKritika
    - /bin/cp main.py $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
